In [1]:
import sys
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import random

plt.rcParams['image.cmap'] = 'gray'
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['figure.figsize'] = (12, 12)

In [2]:
%pylab inline


Populating the interactive namespace from numpy and matplotlib


/home/notshahil/anaconda3/lib/python3.7/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['random']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [3]:
def load_metric(expdir, metric='loss', split='tr', meta=True):
    if meta:
        tr = np.load(expdir + '/meta_{}_{}.npy'.format(split, metric))
    else:
        tr = np.load(expdir + '/{}_{}.npy'.format(split, metric))
    return tr[tr>0]

def smooth(arr, r):
    smoothed = np.zeros(len(arr))
    for i in range(len(arr)/r):
        chunk = arr[i*r:i*r+r]
        avg = np.sum(chunk) / len(chunk)
        smoothed[i*r:i*r+r] = avg
    return smoothed[smoothed >0]

In [4]:
plt.rcParams['figure.figsize'] = (20, 8)

def plot_metrics(expdir0):
    plt.figure()
    
    plt.subplot(1,2,1)
    plt.title('Loss')
    t1, = plt.plot(smooth(load_metric(expdir0, 'loss', 'tr', False), 100))
    t2, = plt.plot(smooth(load_metric(expdir0, 'loss', 'val', False), 100))
    t3, = plt.plot(smooth(load_metric(expdir0, 'loss', 'tr'), 100))
    t4, = plt.plot(smooth(load_metric(expdir0, 'loss', 'val'), 100))
    #plt.ylim((0, 3))
    #plt.xlim((0, 10000))


    plt.subplot(1,2,2)
    t1, = plt.plot(smooth(load_metric(expdir0, 'acc', 'tr', False), 10))
    t2, = plt.plot(smooth(load_metric(expdir0, 'acc', 'val', False), 10))
    t3, = plt.plot(smooth(load_metric(expdir0, 'acc', 'tr'), 10))
    t4, = plt.plot(smooth(load_metric(expdir0, 'acc', 'val'), 10))
    plt.legend([t1, t2, t3, t4], ['train','val', 'm-train', 'm-val'])
    #plt.ylim((0, 1.05))
    #plt.xlim((0, 10000))
    plt.xlabel('Number of iterations')
    plt.ylabel('Accuracy')

In [5]:
expdir0 = '../output/maml-mnist-10way-5shot' 
expdir1 = '../output/maml-omniglot-5way-1shot-adam' 
expdir2 = '../output/maml-omniglot-20way-1shot-adam' 

#plot_metrics(expdir0)
#plot_metrics(expdir1)
#plot_metrics(expdir2)

In [6]:

#plot_metrics(expdir00)

In [42]:
primes = [ 2,3,5,7,  11,  13,  17,  19,  23,  29,  31,  37,  41]

In [43]:

def get_phi(p, k):
    p_ = p
    k_ = k
    phi = 0
    while k_ > 0:
        a = k_ % p
        phi += a/p_
        k_ = int(k_/p)
        p_ *= p
    return phi

In [44]:
import numpy as np
from six import moves

In [45]:
def generate_hammersley(n_dims=1, n_points=5):
    def f():
        for k in moves.range(n_points):
            points = [k/n_points] + [get_phi(primes[d], k) for d in moves.range(n_dims-1)]
            yield points
    return np.array(list(f()))    

In [46]:
x = generate_hammersley

In [48]:
x(1,
  3)

array([[0.        ],
       [0.33333333],
       [0.66666667]])

In [41]:
n_dims=1
n_points = 5
for k in moves.range(n_points):
    dd =[get_phi(primes[d], k) for d in moves.range(n_dims-1)]
    
    print (dd
          )

[]
[]
[]
[]
[]


In [49]:
data =[1,2,3,5,6,7,78,8,8,89,9,9,90]

In [1]:
import copy
import random 

In [34]:
import numpy as np

In [2]:
import chaospy

In [54]:
def Hammersley(num_cls,g_type):
    idxs = [];
    distribution = chaospy.J(chaospy.Uniform(1, len(g_type)))
    pul_sample = distribution.sample(num_cls, rule = "M")
    while len(idxs)<num_cls:

        print(pul_sample)
        #rand=int(random.uniform(0, len(data)))
        #print (rand)
        for i in pul_sample:

            if round(i) in idxs:
                pass
            else:
                idxs.append(round(i));
    #sample=[g_type[j] for j in idxs];
    print (idxs)
    return sample 

In [85]:
def Hammersley(num_cls,g_type):
    idxs = [];
    distribution = chaospy.J(chaospy.Uniform(1, len(g_type)))
    pul_sample = distribution.sample(num_cls, rule = "M")

    print(pul_sample)
    for i in pul_sample:
        idxs.append(int((i)))
        
    indexes = np.unique(idxs, return_index=True)[1]
    unsort = [idxs[index] for index in sorted(indexes)]
    
    sample=[g_type[j] for j in idxs];
    return sample

In [89]:
g_type=['yy','rr', 'ee','qq','s','www','ereee','rrr','ttt','ttt','eee','tre','wgh','wfger','dddd','eeeeee','tttttt','yyyyyy','rrrrrrrrr','fgf']

In [65]:
#d =chaospy.J(chaospy.Uniform(0, 20))

In [66]:
#d.sample(5)

In [90]:
s = Hammersley(5,g_type)

[15.25   3.375 12.875  8.125 17.625]


In [91]:
s

['eeeeee', 'qq', 'wgh', 'ttt', 'yyyyyy']

In [84]:
a=np.unique(s)

In [81]:
a

array([ 2,  5,  9, 10, 12])

In [82]:
b


array([1, 3, 2, 0, 4])

In [ ]:
ex_17 = "17. Sampling by taking samples from a uniform distribution, \
 and treat them as the random generated index.";
def sampling_17(data, n=num_cls):
    idxs = [];
    while len(idxs)<n:
        distribution = chaospy.J(chaospy.Uniform(0, len(data)))
        pul_sample = distribution.sample(num_cls, rule = "M")
        rand=int(random.uniform(0, len(data)))
        if rand in idxs:
            pass
        else:
            idxs.append(rand);
    sample=[data[i] for i in idxs];
    return sample